apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: the-crew
servers: 1
agents: 0
registries:
  use:
    - k3d-the-crew-registry:5050
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
