/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdOrgRouteImport } from './routes/projects/$projectId/org'
import { Route as ProjectsProjectIdDiffRouteImport } from './routes/projects/$projectId/diff'
import { Route as ProjectsProjectIdAdminRouteImport } from './routes/projects/$projectId/admin'
import { Route as ProjectsProjectIdWorkflowsWorkflowIdRouteImport } from './routes/projects/$projectId/workflows.$workflowId'
import { Route as ProjectsProjectIdDepartmentsDepartmentIdRouteImport } from './routes/projects/$projectId/departments.$departmentId'
import { Route as ProjectsProjectIdAdminWorkflowsRouteImport } from './routes/projects/$projectId/admin/workflows'
import { Route as ProjectsProjectIdAdminValidationsRouteImport } from './routes/projects/$projectId/admin/validations'
import { Route as ProjectsProjectIdAdminSkillsRouteImport } from './routes/projects/$projectId/admin/skills'
import { Route as ProjectsProjectIdAdminRolesRouteImport } from './routes/projects/$projectId/admin/roles'
import { Route as ProjectsProjectIdAdminReleasesRouteImport } from './routes/projects/$projectId/admin/releases'
import { Route as ProjectsProjectIdAdminPoliciesRouteImport } from './routes/projects/$projectId/admin/policies'
import { Route as ProjectsProjectIdAdminOverviewRouteImport } from './routes/projects/$projectId/admin/overview'
import { Route as ProjectsProjectIdAdminDepartmentsRouteImport } from './routes/projects/$projectId/admin/departments'
import { Route as ProjectsProjectIdAdminContractsRouteImport } from './routes/projects/$projectId/admin/contracts'
import { Route as ProjectsProjectIdAdminCompanyModelRouteImport } from './routes/projects/$projectId/admin/company-model'
import { Route as ProjectsProjectIdAdminCapabilitiesRouteImport } from './routes/projects/$projectId/admin/capabilities'
import { Route as ProjectsProjectIdAdminAuditRouteImport } from './routes/projects/$projectId/admin/audit'
import { Route as ProjectsProjectIdAdminAgentsRouteImport } from './routes/projects/$projectId/admin/agents'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdOrgRoute = ProjectsProjectIdOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdDiffRoute = ProjectsProjectIdDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdAdminRoute = ProjectsProjectIdAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdWorkflowsWorkflowIdRoute =
  ProjectsProjectIdWorkflowsWorkflowIdRouteImport.update({
    id: '/workflows/$workflowId',
    path: '/workflows/$workflowId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdDepartmentsDepartmentIdRoute =
  ProjectsProjectIdDepartmentsDepartmentIdRouteImport.update({
    id: '/departments/$departmentId',
    path: '/departments/$departmentId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdAdminWorkflowsRoute =
  ProjectsProjectIdAdminWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => ProjectsProjectIdAdminRoute,
  } as any)
const ProjectsProjectIdAdminValidationsRoute =
  ProjectsProjectIdAdminValidationsRouteImport.update({
    id: '/validations',
    path: '/validations',
    getParentRoute: () => ProjectsProjectIdAdminRoute,
  } as any)
const ProjectsProjectIdAdminSkillsRoute =
  ProjectsProjectIdAdminSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => ProjectsProjectIdAdminRoute,
  } as any)
const ProjectsProjectIdAdminRolesRoute =
  ProjectsProjectIdAdminRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => ProjectsProjectIdAdminRoute,
  } as any)
const ProjectsProjectIdAdminReleasesRoute =
  ProjectsProjectIdAdminReleasesRouteImport.update({
    id: '/releases',
    path: '/releases',
    getParentRoute: () => ProjectsProjectIdAdminRoute,
  } as any)
const ProjectsProjectIdAdminPoliciesRoute =
  ProjectsProjectIdAdminPoliciesRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => ProjectsProjectIdAdminRoute,
  } as any)
const ProjectsProjectIdAdminOverviewRoute =
  ProjectsProjectIdAdminOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ProjectsProjectIdAdminRoute,
  } as any)
const ProjectsProjectIdAdminDepartmentsRoute =
  ProjectsProjectIdAdminDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => ProjectsProjectIdAdminRoute,
  } as any)
const ProjectsProjectIdAdminContractsRoute =
  ProjectsProjectIdAdminContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => ProjectsProjectIdAdminRoute,
  } as any)
const ProjectsProjectIdAdminCompanyModelRoute =
  ProjectsProjectIdAdminCompanyModelRouteImport.update({
    id: '/company-model',
    path: '/company-model',
    getParentRoute: () => ProjectsProjectIdAdminRoute,
  } as any)
const ProjectsProjectIdAdminCapabilitiesRoute =
  ProjectsProjectIdAdminCapabilitiesRouteImport.update({
    id: '/capabilities',
    path: '/capabilities',
    getParentRoute: () => ProjectsProjectIdAdminRoute,
  } as any)
const ProjectsProjectIdAdminAuditRoute =
  ProjectsProjectIdAdminAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => ProjectsProjectIdAdminRoute,
  } as any)
const ProjectsProjectIdAdminAgentsRoute =
  ProjectsProjectIdAdminAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => ProjectsProjectIdAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/admin': typeof ProjectsProjectIdAdminRouteWithChildren
  '/projects/$projectId/diff': typeof ProjectsProjectIdDiffRoute
  '/projects/$projectId/org': typeof ProjectsProjectIdOrgRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/admin/agents': typeof ProjectsProjectIdAdminAgentsRoute
  '/projects/$projectId/admin/audit': typeof ProjectsProjectIdAdminAuditRoute
  '/projects/$projectId/admin/capabilities': typeof ProjectsProjectIdAdminCapabilitiesRoute
  '/projects/$projectId/admin/company-model': typeof ProjectsProjectIdAdminCompanyModelRoute
  '/projects/$projectId/admin/contracts': typeof ProjectsProjectIdAdminContractsRoute
  '/projects/$projectId/admin/departments': typeof ProjectsProjectIdAdminDepartmentsRoute
  '/projects/$projectId/admin/overview': typeof ProjectsProjectIdAdminOverviewRoute
  '/projects/$projectId/admin/policies': typeof ProjectsProjectIdAdminPoliciesRoute
  '/projects/$projectId/admin/releases': typeof ProjectsProjectIdAdminReleasesRoute
  '/projects/$projectId/admin/roles': typeof ProjectsProjectIdAdminRolesRoute
  '/projects/$projectId/admin/skills': typeof ProjectsProjectIdAdminSkillsRoute
  '/projects/$projectId/admin/validations': typeof ProjectsProjectIdAdminValidationsRoute
  '/projects/$projectId/admin/workflows': typeof ProjectsProjectIdAdminWorkflowsRoute
  '/projects/$projectId/departments/$departmentId': typeof ProjectsProjectIdDepartmentsDepartmentIdRoute
  '/projects/$projectId/workflows/$workflowId': typeof ProjectsProjectIdWorkflowsWorkflowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/$projectId/admin': typeof ProjectsProjectIdAdminRouteWithChildren
  '/projects/$projectId/diff': typeof ProjectsProjectIdDiffRoute
  '/projects/$projectId/org': typeof ProjectsProjectIdOrgRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/admin/agents': typeof ProjectsProjectIdAdminAgentsRoute
  '/projects/$projectId/admin/audit': typeof ProjectsProjectIdAdminAuditRoute
  '/projects/$projectId/admin/capabilities': typeof ProjectsProjectIdAdminCapabilitiesRoute
  '/projects/$projectId/admin/company-model': typeof ProjectsProjectIdAdminCompanyModelRoute
  '/projects/$projectId/admin/contracts': typeof ProjectsProjectIdAdminContractsRoute
  '/projects/$projectId/admin/departments': typeof ProjectsProjectIdAdminDepartmentsRoute
  '/projects/$projectId/admin/overview': typeof ProjectsProjectIdAdminOverviewRoute
  '/projects/$projectId/admin/policies': typeof ProjectsProjectIdAdminPoliciesRoute
  '/projects/$projectId/admin/releases': typeof ProjectsProjectIdAdminReleasesRoute
  '/projects/$projectId/admin/roles': typeof ProjectsProjectIdAdminRolesRoute
  '/projects/$projectId/admin/skills': typeof ProjectsProjectIdAdminSkillsRoute
  '/projects/$projectId/admin/validations': typeof ProjectsProjectIdAdminValidationsRoute
  '/projects/$projectId/admin/workflows': typeof ProjectsProjectIdAdminWorkflowsRoute
  '/projects/$projectId/departments/$departmentId': typeof ProjectsProjectIdDepartmentsDepartmentIdRoute
  '/projects/$projectId/workflows/$workflowId': typeof ProjectsProjectIdWorkflowsWorkflowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/admin': typeof ProjectsProjectIdAdminRouteWithChildren
  '/projects/$projectId/diff': typeof ProjectsProjectIdDiffRoute
  '/projects/$projectId/org': typeof ProjectsProjectIdOrgRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/admin/agents': typeof ProjectsProjectIdAdminAgentsRoute
  '/projects/$projectId/admin/audit': typeof ProjectsProjectIdAdminAuditRoute
  '/projects/$projectId/admin/capabilities': typeof ProjectsProjectIdAdminCapabilitiesRoute
  '/projects/$projectId/admin/company-model': typeof ProjectsProjectIdAdminCompanyModelRoute
  '/projects/$projectId/admin/contracts': typeof ProjectsProjectIdAdminContractsRoute
  '/projects/$projectId/admin/departments': typeof ProjectsProjectIdAdminDepartmentsRoute
  '/projects/$projectId/admin/overview': typeof ProjectsProjectIdAdminOverviewRoute
  '/projects/$projectId/admin/policies': typeof ProjectsProjectIdAdminPoliciesRoute
  '/projects/$projectId/admin/releases': typeof ProjectsProjectIdAdminReleasesRoute
  '/projects/$projectId/admin/roles': typeof ProjectsProjectIdAdminRolesRoute
  '/projects/$projectId/admin/skills': typeof ProjectsProjectIdAdminSkillsRoute
  '/projects/$projectId/admin/validations': typeof ProjectsProjectIdAdminValidationsRoute
  '/projects/$projectId/admin/workflows': typeof ProjectsProjectIdAdminWorkflowsRoute
  '/projects/$projectId/departments/$departmentId': typeof ProjectsProjectIdDepartmentsDepartmentIdRoute
  '/projects/$projectId/workflows/$workflowId': typeof ProjectsProjectIdWorkflowsWorkflowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/$projectId'
    | '/projects/$projectId/admin'
    | '/projects/$projectId/diff'
    | '/projects/$projectId/org'
    | '/projects/$projectId/'
    | '/projects/$projectId/admin/agents'
    | '/projects/$projectId/admin/audit'
    | '/projects/$projectId/admin/capabilities'
    | '/projects/$projectId/admin/company-model'
    | '/projects/$projectId/admin/contracts'
    | '/projects/$projectId/admin/departments'
    | '/projects/$projectId/admin/overview'
    | '/projects/$projectId/admin/policies'
    | '/projects/$projectId/admin/releases'
    | '/projects/$projectId/admin/roles'
    | '/projects/$projectId/admin/skills'
    | '/projects/$projectId/admin/validations'
    | '/projects/$projectId/admin/workflows'
    | '/projects/$projectId/departments/$departmentId'
    | '/projects/$projectId/workflows/$workflowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/$projectId/admin'
    | '/projects/$projectId/diff'
    | '/projects/$projectId/org'
    | '/projects/$projectId'
    | '/projects/$projectId/admin/agents'
    | '/projects/$projectId/admin/audit'
    | '/projects/$projectId/admin/capabilities'
    | '/projects/$projectId/admin/company-model'
    | '/projects/$projectId/admin/contracts'
    | '/projects/$projectId/admin/departments'
    | '/projects/$projectId/admin/overview'
    | '/projects/$projectId/admin/policies'
    | '/projects/$projectId/admin/releases'
    | '/projects/$projectId/admin/roles'
    | '/projects/$projectId/admin/skills'
    | '/projects/$projectId/admin/validations'
    | '/projects/$projectId/admin/workflows'
    | '/projects/$projectId/departments/$departmentId'
    | '/projects/$projectId/workflows/$workflowId'
  id:
    | '__root__'
    | '/'
    | '/projects/$projectId'
    | '/projects/$projectId/admin'
    | '/projects/$projectId/diff'
    | '/projects/$projectId/org'
    | '/projects/$projectId/'
    | '/projects/$projectId/admin/agents'
    | '/projects/$projectId/admin/audit'
    | '/projects/$projectId/admin/capabilities'
    | '/projects/$projectId/admin/company-model'
    | '/projects/$projectId/admin/contracts'
    | '/projects/$projectId/admin/departments'
    | '/projects/$projectId/admin/overview'
    | '/projects/$projectId/admin/policies'
    | '/projects/$projectId/admin/releases'
    | '/projects/$projectId/admin/roles'
    | '/projects/$projectId/admin/skills'
    | '/projects/$projectId/admin/validations'
    | '/projects/$projectId/admin/workflows'
    | '/projects/$projectId/departments/$departmentId'
    | '/projects/$projectId/workflows/$workflowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/org': {
      id: '/projects/$projectId/org'
      path: '/org'
      fullPath: '/projects/$projectId/org'
      preLoaderRoute: typeof ProjectsProjectIdOrgRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/diff': {
      id: '/projects/$projectId/diff'
      path: '/diff'
      fullPath: '/projects/$projectId/diff'
      preLoaderRoute: typeof ProjectsProjectIdDiffRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/admin': {
      id: '/projects/$projectId/admin'
      path: '/admin'
      fullPath: '/projects/$projectId/admin'
      preLoaderRoute: typeof ProjectsProjectIdAdminRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/workflows/$workflowId': {
      id: '/projects/$projectId/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/projects/$projectId/workflows/$workflowId'
      preLoaderRoute: typeof ProjectsProjectIdWorkflowsWorkflowIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/departments/$departmentId': {
      id: '/projects/$projectId/departments/$departmentId'
      path: '/departments/$departmentId'
      fullPath: '/projects/$projectId/departments/$departmentId'
      preLoaderRoute: typeof ProjectsProjectIdDepartmentsDepartmentIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/admin/workflows': {
      id: '/projects/$projectId/admin/workflows'
      path: '/workflows'
      fullPath: '/projects/$projectId/admin/workflows'
      preLoaderRoute: typeof ProjectsProjectIdAdminWorkflowsRouteImport
      parentRoute: typeof ProjectsProjectIdAdminRoute
    }
    '/projects/$projectId/admin/validations': {
      id: '/projects/$projectId/admin/validations'
      path: '/validations'
      fullPath: '/projects/$projectId/admin/validations'
      preLoaderRoute: typeof ProjectsProjectIdAdminValidationsRouteImport
      parentRoute: typeof ProjectsProjectIdAdminRoute
    }
    '/projects/$projectId/admin/skills': {
      id: '/projects/$projectId/admin/skills'
      path: '/skills'
      fullPath: '/projects/$projectId/admin/skills'
      preLoaderRoute: typeof ProjectsProjectIdAdminSkillsRouteImport
      parentRoute: typeof ProjectsProjectIdAdminRoute
    }
    '/projects/$projectId/admin/roles': {
      id: '/projects/$projectId/admin/roles'
      path: '/roles'
      fullPath: '/projects/$projectId/admin/roles'
      preLoaderRoute: typeof ProjectsProjectIdAdminRolesRouteImport
      parentRoute: typeof ProjectsProjectIdAdminRoute
    }
    '/projects/$projectId/admin/releases': {
      id: '/projects/$projectId/admin/releases'
      path: '/releases'
      fullPath: '/projects/$projectId/admin/releases'
      preLoaderRoute: typeof ProjectsProjectIdAdminReleasesRouteImport
      parentRoute: typeof ProjectsProjectIdAdminRoute
    }
    '/projects/$projectId/admin/policies': {
      id: '/projects/$projectId/admin/policies'
      path: '/policies'
      fullPath: '/projects/$projectId/admin/policies'
      preLoaderRoute: typeof ProjectsProjectIdAdminPoliciesRouteImport
      parentRoute: typeof ProjectsProjectIdAdminRoute
    }
    '/projects/$projectId/admin/overview': {
      id: '/projects/$projectId/admin/overview'
      path: '/overview'
      fullPath: '/projects/$projectId/admin/overview'
      preLoaderRoute: typeof ProjectsProjectIdAdminOverviewRouteImport
      parentRoute: typeof ProjectsProjectIdAdminRoute
    }
    '/projects/$projectId/admin/departments': {
      id: '/projects/$projectId/admin/departments'
      path: '/departments'
      fullPath: '/projects/$projectId/admin/departments'
      preLoaderRoute: typeof ProjectsProjectIdAdminDepartmentsRouteImport
      parentRoute: typeof ProjectsProjectIdAdminRoute
    }
    '/projects/$projectId/admin/contracts': {
      id: '/projects/$projectId/admin/contracts'
      path: '/contracts'
      fullPath: '/projects/$projectId/admin/contracts'
      preLoaderRoute: typeof ProjectsProjectIdAdminContractsRouteImport
      parentRoute: typeof ProjectsProjectIdAdminRoute
    }
    '/projects/$projectId/admin/company-model': {
      id: '/projects/$projectId/admin/company-model'
      path: '/company-model'
      fullPath: '/projects/$projectId/admin/company-model'
      preLoaderRoute: typeof ProjectsProjectIdAdminCompanyModelRouteImport
      parentRoute: typeof ProjectsProjectIdAdminRoute
    }
    '/projects/$projectId/admin/capabilities': {
      id: '/projects/$projectId/admin/capabilities'
      path: '/capabilities'
      fullPath: '/projects/$projectId/admin/capabilities'
      preLoaderRoute: typeof ProjectsProjectIdAdminCapabilitiesRouteImport
      parentRoute: typeof ProjectsProjectIdAdminRoute
    }
    '/projects/$projectId/admin/audit': {
      id: '/projects/$projectId/admin/audit'
      path: '/audit'
      fullPath: '/projects/$projectId/admin/audit'
      preLoaderRoute: typeof ProjectsProjectIdAdminAuditRouteImport
      parentRoute: typeof ProjectsProjectIdAdminRoute
    }
    '/projects/$projectId/admin/agents': {
      id: '/projects/$projectId/admin/agents'
      path: '/agents'
      fullPath: '/projects/$projectId/admin/agents'
      preLoaderRoute: typeof ProjectsProjectIdAdminAgentsRouteImport
      parentRoute: typeof ProjectsProjectIdAdminRoute
    }
  }
}

interface ProjectsProjectIdAdminRouteChildren {
  ProjectsProjectIdAdminAgentsRoute: typeof ProjectsProjectIdAdminAgentsRoute
  ProjectsProjectIdAdminAuditRoute: typeof ProjectsProjectIdAdminAuditRoute
  ProjectsProjectIdAdminCapabilitiesRoute: typeof ProjectsProjectIdAdminCapabilitiesRoute
  ProjectsProjectIdAdminCompanyModelRoute: typeof ProjectsProjectIdAdminCompanyModelRoute
  ProjectsProjectIdAdminContractsRoute: typeof ProjectsProjectIdAdminContractsRoute
  ProjectsProjectIdAdminDepartmentsRoute: typeof ProjectsProjectIdAdminDepartmentsRoute
  ProjectsProjectIdAdminOverviewRoute: typeof ProjectsProjectIdAdminOverviewRoute
  ProjectsProjectIdAdminPoliciesRoute: typeof ProjectsProjectIdAdminPoliciesRoute
  ProjectsProjectIdAdminReleasesRoute: typeof ProjectsProjectIdAdminReleasesRoute
  ProjectsProjectIdAdminRolesRoute: typeof ProjectsProjectIdAdminRolesRoute
  ProjectsProjectIdAdminSkillsRoute: typeof ProjectsProjectIdAdminSkillsRoute
  ProjectsProjectIdAdminValidationsRoute: typeof ProjectsProjectIdAdminValidationsRoute
  ProjectsProjectIdAdminWorkflowsRoute: typeof ProjectsProjectIdAdminWorkflowsRoute
}

const ProjectsProjectIdAdminRouteChildren: ProjectsProjectIdAdminRouteChildren =
  {
    ProjectsProjectIdAdminAgentsRoute: ProjectsProjectIdAdminAgentsRoute,
    ProjectsProjectIdAdminAuditRoute: ProjectsProjectIdAdminAuditRoute,
    ProjectsProjectIdAdminCapabilitiesRoute:
      ProjectsProjectIdAdminCapabilitiesRoute,
    ProjectsProjectIdAdminCompanyModelRoute:
      ProjectsProjectIdAdminCompanyModelRoute,
    ProjectsProjectIdAdminContractsRoute: ProjectsProjectIdAdminContractsRoute,
    ProjectsProjectIdAdminDepartmentsRoute:
      ProjectsProjectIdAdminDepartmentsRoute,
    ProjectsProjectIdAdminOverviewRoute: ProjectsProjectIdAdminOverviewRoute,
    ProjectsProjectIdAdminPoliciesRoute: ProjectsProjectIdAdminPoliciesRoute,
    ProjectsProjectIdAdminReleasesRoute: ProjectsProjectIdAdminReleasesRoute,
    ProjectsProjectIdAdminRolesRoute: ProjectsProjectIdAdminRolesRoute,
    ProjectsProjectIdAdminSkillsRoute: ProjectsProjectIdAdminSkillsRoute,
    ProjectsProjectIdAdminValidationsRoute:
      ProjectsProjectIdAdminValidationsRoute,
    ProjectsProjectIdAdminWorkflowsRoute: ProjectsProjectIdAdminWorkflowsRoute,
  }

const ProjectsProjectIdAdminRouteWithChildren =
  ProjectsProjectIdAdminRoute._addFileChildren(
    ProjectsProjectIdAdminRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdAdminRoute: typeof ProjectsProjectIdAdminRouteWithChildren
  ProjectsProjectIdDiffRoute: typeof ProjectsProjectIdDiffRoute
  ProjectsProjectIdOrgRoute: typeof ProjectsProjectIdOrgRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdDepartmentsDepartmentIdRoute: typeof ProjectsProjectIdDepartmentsDepartmentIdRoute
  ProjectsProjectIdWorkflowsWorkflowIdRoute: typeof ProjectsProjectIdWorkflowsWorkflowIdRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdAdminRoute: ProjectsProjectIdAdminRouteWithChildren,
  ProjectsProjectIdDiffRoute: ProjectsProjectIdDiffRoute,
  ProjectsProjectIdOrgRoute: ProjectsProjectIdOrgRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdDepartmentsDepartmentIdRoute:
    ProjectsProjectIdDepartmentsDepartmentIdRoute,
  ProjectsProjectIdWorkflowsWorkflowIdRoute:
    ProjectsProjectIdWorkflowsWorkflowIdRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
