/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsProjectSlugRouteImport } from './routes/projects/$projectSlug'
import { Route as ProjectsProjectSlugIndexRouteImport } from './routes/projects/$projectSlug/index'
import { Route as ProjectsProjectSlugOrgRouteImport } from './routes/projects/$projectSlug/org'
import { Route as ProjectsProjectSlugDiffRouteImport } from './routes/projects/$projectSlug/diff'
import { Route as ProjectsProjectSlugAdminRouteImport } from './routes/projects/$projectSlug/admin'
import { Route as ProjectsProjectSlugWorkflowsWorkflowIdRouteImport } from './routes/projects/$projectSlug/workflows.$workflowId'
import { Route as ProjectsProjectSlugDepartmentsDepartmentIdRouteImport } from './routes/projects/$projectSlug/departments.$departmentId'
import { Route as ProjectsProjectSlugAdminWorkflowsRouteImport } from './routes/projects/$projectSlug/admin/workflows'
import { Route as ProjectsProjectSlugAdminValidationsRouteImport } from './routes/projects/$projectSlug/admin/validations'
import { Route as ProjectsProjectSlugAdminSkillsRouteImport } from './routes/projects/$projectSlug/admin/skills'
import { Route as ProjectsProjectSlugAdminRolesRouteImport } from './routes/projects/$projectSlug/admin/roles'
import { Route as ProjectsProjectSlugAdminReleasesRouteImport } from './routes/projects/$projectSlug/admin/releases'
import { Route as ProjectsProjectSlugAdminPoliciesRouteImport } from './routes/projects/$projectSlug/admin/policies'
import { Route as ProjectsProjectSlugAdminOverviewRouteImport } from './routes/projects/$projectSlug/admin/overview'
import { Route as ProjectsProjectSlugAdminDepartmentsRouteImport } from './routes/projects/$projectSlug/admin/departments'
import { Route as ProjectsProjectSlugAdminContractsRouteImport } from './routes/projects/$projectSlug/admin/contracts'
import { Route as ProjectsProjectSlugAdminCompanyModelRouteImport } from './routes/projects/$projectSlug/admin/company-model'
import { Route as ProjectsProjectSlugAdminCapabilitiesRouteImport } from './routes/projects/$projectSlug/admin/capabilities'
import { Route as ProjectsProjectSlugAdminAuditRouteImport } from './routes/projects/$projectSlug/admin/audit'
import { Route as ProjectsProjectSlugAdminAgentsRouteImport } from './routes/projects/$projectSlug/admin/agents'
import { Route as ProjectsProjectSlugWorkflowsWorkflowIdStagesStageIdRouteImport } from './routes/projects/$projectSlug/workflows.$workflowId.stages.$stageId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectSlugRoute = ProjectsProjectSlugRouteImport.update({
  id: '/projects/$projectSlug',
  path: '/projects/$projectSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectSlugIndexRoute =
  ProjectsProjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectSlugRoute,
  } as any)
const ProjectsProjectSlugOrgRoute = ProjectsProjectSlugOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => ProjectsProjectSlugRoute,
} as any)
const ProjectsProjectSlugDiffRoute = ProjectsProjectSlugDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => ProjectsProjectSlugRoute,
} as any)
const ProjectsProjectSlugAdminRoute =
  ProjectsProjectSlugAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => ProjectsProjectSlugRoute,
  } as any)
const ProjectsProjectSlugWorkflowsWorkflowIdRoute =
  ProjectsProjectSlugWorkflowsWorkflowIdRouteImport.update({
    id: '/workflows/$workflowId',
    path: '/workflows/$workflowId',
    getParentRoute: () => ProjectsProjectSlugRoute,
  } as any)
const ProjectsProjectSlugDepartmentsDepartmentIdRoute =
  ProjectsProjectSlugDepartmentsDepartmentIdRouteImport.update({
    id: '/departments/$departmentId',
    path: '/departments/$departmentId',
    getParentRoute: () => ProjectsProjectSlugRoute,
  } as any)
const ProjectsProjectSlugAdminWorkflowsRoute =
  ProjectsProjectSlugAdminWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => ProjectsProjectSlugAdminRoute,
  } as any)
const ProjectsProjectSlugAdminValidationsRoute =
  ProjectsProjectSlugAdminValidationsRouteImport.update({
    id: '/validations',
    path: '/validations',
    getParentRoute: () => ProjectsProjectSlugAdminRoute,
  } as any)
const ProjectsProjectSlugAdminSkillsRoute =
  ProjectsProjectSlugAdminSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => ProjectsProjectSlugAdminRoute,
  } as any)
const ProjectsProjectSlugAdminRolesRoute =
  ProjectsProjectSlugAdminRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => ProjectsProjectSlugAdminRoute,
  } as any)
const ProjectsProjectSlugAdminReleasesRoute =
  ProjectsProjectSlugAdminReleasesRouteImport.update({
    id: '/releases',
    path: '/releases',
    getParentRoute: () => ProjectsProjectSlugAdminRoute,
  } as any)
const ProjectsProjectSlugAdminPoliciesRoute =
  ProjectsProjectSlugAdminPoliciesRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => ProjectsProjectSlugAdminRoute,
  } as any)
const ProjectsProjectSlugAdminOverviewRoute =
  ProjectsProjectSlugAdminOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ProjectsProjectSlugAdminRoute,
  } as any)
const ProjectsProjectSlugAdminDepartmentsRoute =
  ProjectsProjectSlugAdminDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => ProjectsProjectSlugAdminRoute,
  } as any)
const ProjectsProjectSlugAdminContractsRoute =
  ProjectsProjectSlugAdminContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => ProjectsProjectSlugAdminRoute,
  } as any)
const ProjectsProjectSlugAdminCompanyModelRoute =
  ProjectsProjectSlugAdminCompanyModelRouteImport.update({
    id: '/company-model',
    path: '/company-model',
    getParentRoute: () => ProjectsProjectSlugAdminRoute,
  } as any)
const ProjectsProjectSlugAdminCapabilitiesRoute =
  ProjectsProjectSlugAdminCapabilitiesRouteImport.update({
    id: '/capabilities',
    path: '/capabilities',
    getParentRoute: () => ProjectsProjectSlugAdminRoute,
  } as any)
const ProjectsProjectSlugAdminAuditRoute =
  ProjectsProjectSlugAdminAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => ProjectsProjectSlugAdminRoute,
  } as any)
const ProjectsProjectSlugAdminAgentsRoute =
  ProjectsProjectSlugAdminAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => ProjectsProjectSlugAdminRoute,
  } as any)
const ProjectsProjectSlugWorkflowsWorkflowIdStagesStageIdRoute =
  ProjectsProjectSlugWorkflowsWorkflowIdStagesStageIdRouteImport.update({
    id: '/stages/$stageId',
    path: '/stages/$stageId',
    getParentRoute: () => ProjectsProjectSlugWorkflowsWorkflowIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectSlug/admin': typeof ProjectsProjectSlugAdminRouteWithChildren
  '/projects/$projectSlug/diff': typeof ProjectsProjectSlugDiffRoute
  '/projects/$projectSlug/org': typeof ProjectsProjectSlugOrgRoute
  '/projects/$projectSlug/': typeof ProjectsProjectSlugIndexRoute
  '/projects/$projectSlug/admin/agents': typeof ProjectsProjectSlugAdminAgentsRoute
  '/projects/$projectSlug/admin/audit': typeof ProjectsProjectSlugAdminAuditRoute
  '/projects/$projectSlug/admin/capabilities': typeof ProjectsProjectSlugAdminCapabilitiesRoute
  '/projects/$projectSlug/admin/company-model': typeof ProjectsProjectSlugAdminCompanyModelRoute
  '/projects/$projectSlug/admin/contracts': typeof ProjectsProjectSlugAdminContractsRoute
  '/projects/$projectSlug/admin/departments': typeof ProjectsProjectSlugAdminDepartmentsRoute
  '/projects/$projectSlug/admin/overview': typeof ProjectsProjectSlugAdminOverviewRoute
  '/projects/$projectSlug/admin/policies': typeof ProjectsProjectSlugAdminPoliciesRoute
  '/projects/$projectSlug/admin/releases': typeof ProjectsProjectSlugAdminReleasesRoute
  '/projects/$projectSlug/admin/roles': typeof ProjectsProjectSlugAdminRolesRoute
  '/projects/$projectSlug/admin/skills': typeof ProjectsProjectSlugAdminSkillsRoute
  '/projects/$projectSlug/admin/validations': typeof ProjectsProjectSlugAdminValidationsRoute
  '/projects/$projectSlug/admin/workflows': typeof ProjectsProjectSlugAdminWorkflowsRoute
  '/projects/$projectSlug/departments/$departmentId': typeof ProjectsProjectSlugDepartmentsDepartmentIdRoute
  '/projects/$projectSlug/workflows/$workflowId': typeof ProjectsProjectSlugWorkflowsWorkflowIdRouteWithChildren
  '/projects/$projectSlug/workflows/$workflowId/stages/$stageId': typeof ProjectsProjectSlugWorkflowsWorkflowIdStagesStageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectSlug/admin': typeof ProjectsProjectSlugAdminRouteWithChildren
  '/projects/$projectSlug/diff': typeof ProjectsProjectSlugDiffRoute
  '/projects/$projectSlug/org': typeof ProjectsProjectSlugOrgRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugIndexRoute
  '/projects/$projectSlug/admin/agents': typeof ProjectsProjectSlugAdminAgentsRoute
  '/projects/$projectSlug/admin/audit': typeof ProjectsProjectSlugAdminAuditRoute
  '/projects/$projectSlug/admin/capabilities': typeof ProjectsProjectSlugAdminCapabilitiesRoute
  '/projects/$projectSlug/admin/company-model': typeof ProjectsProjectSlugAdminCompanyModelRoute
  '/projects/$projectSlug/admin/contracts': typeof ProjectsProjectSlugAdminContractsRoute
  '/projects/$projectSlug/admin/departments': typeof ProjectsProjectSlugAdminDepartmentsRoute
  '/projects/$projectSlug/admin/overview': typeof ProjectsProjectSlugAdminOverviewRoute
  '/projects/$projectSlug/admin/policies': typeof ProjectsProjectSlugAdminPoliciesRoute
  '/projects/$projectSlug/admin/releases': typeof ProjectsProjectSlugAdminReleasesRoute
  '/projects/$projectSlug/admin/roles': typeof ProjectsProjectSlugAdminRolesRoute
  '/projects/$projectSlug/admin/skills': typeof ProjectsProjectSlugAdminSkillsRoute
  '/projects/$projectSlug/admin/validations': typeof ProjectsProjectSlugAdminValidationsRoute
  '/projects/$projectSlug/admin/workflows': typeof ProjectsProjectSlugAdminWorkflowsRoute
  '/projects/$projectSlug/departments/$departmentId': typeof ProjectsProjectSlugDepartmentsDepartmentIdRoute
  '/projects/$projectSlug/workflows/$workflowId': typeof ProjectsProjectSlugWorkflowsWorkflowIdRouteWithChildren
  '/projects/$projectSlug/workflows/$workflowId/stages/$stageId': typeof ProjectsProjectSlugWorkflowsWorkflowIdStagesStageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectSlug/admin': typeof ProjectsProjectSlugAdminRouteWithChildren
  '/projects/$projectSlug/diff': typeof ProjectsProjectSlugDiffRoute
  '/projects/$projectSlug/org': typeof ProjectsProjectSlugOrgRoute
  '/projects/$projectSlug/': typeof ProjectsProjectSlugIndexRoute
  '/projects/$projectSlug/admin/agents': typeof ProjectsProjectSlugAdminAgentsRoute
  '/projects/$projectSlug/admin/audit': typeof ProjectsProjectSlugAdminAuditRoute
  '/projects/$projectSlug/admin/capabilities': typeof ProjectsProjectSlugAdminCapabilitiesRoute
  '/projects/$projectSlug/admin/company-model': typeof ProjectsProjectSlugAdminCompanyModelRoute
  '/projects/$projectSlug/admin/contracts': typeof ProjectsProjectSlugAdminContractsRoute
  '/projects/$projectSlug/admin/departments': typeof ProjectsProjectSlugAdminDepartmentsRoute
  '/projects/$projectSlug/admin/overview': typeof ProjectsProjectSlugAdminOverviewRoute
  '/projects/$projectSlug/admin/policies': typeof ProjectsProjectSlugAdminPoliciesRoute
  '/projects/$projectSlug/admin/releases': typeof ProjectsProjectSlugAdminReleasesRoute
  '/projects/$projectSlug/admin/roles': typeof ProjectsProjectSlugAdminRolesRoute
  '/projects/$projectSlug/admin/skills': typeof ProjectsProjectSlugAdminSkillsRoute
  '/projects/$projectSlug/admin/validations': typeof ProjectsProjectSlugAdminValidationsRoute
  '/projects/$projectSlug/admin/workflows': typeof ProjectsProjectSlugAdminWorkflowsRoute
  '/projects/$projectSlug/departments/$departmentId': typeof ProjectsProjectSlugDepartmentsDepartmentIdRoute
  '/projects/$projectSlug/workflows/$workflowId': typeof ProjectsProjectSlugWorkflowsWorkflowIdRouteWithChildren
  '/projects/$projectSlug/workflows/$workflowId/stages/$stageId': typeof ProjectsProjectSlugWorkflowsWorkflowIdStagesStageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/projects/$projectSlug'
    | '/projects/new'
    | '/projects/$projectSlug/admin'
    | '/projects/$projectSlug/diff'
    | '/projects/$projectSlug/org'
    | '/projects/$projectSlug/'
    | '/projects/$projectSlug/admin/agents'
    | '/projects/$projectSlug/admin/audit'
    | '/projects/$projectSlug/admin/capabilities'
    | '/projects/$projectSlug/admin/company-model'
    | '/projects/$projectSlug/admin/contracts'
    | '/projects/$projectSlug/admin/departments'
    | '/projects/$projectSlug/admin/overview'
    | '/projects/$projectSlug/admin/policies'
    | '/projects/$projectSlug/admin/releases'
    | '/projects/$projectSlug/admin/roles'
    | '/projects/$projectSlug/admin/skills'
    | '/projects/$projectSlug/admin/validations'
    | '/projects/$projectSlug/admin/workflows'
    | '/projects/$projectSlug/departments/$departmentId'
    | '/projects/$projectSlug/workflows/$workflowId'
    | '/projects/$projectSlug/workflows/$workflowId/stages/$stageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/projects/new'
    | '/projects/$projectSlug/admin'
    | '/projects/$projectSlug/diff'
    | '/projects/$projectSlug/org'
    | '/projects/$projectSlug'
    | '/projects/$projectSlug/admin/agents'
    | '/projects/$projectSlug/admin/audit'
    | '/projects/$projectSlug/admin/capabilities'
    | '/projects/$projectSlug/admin/company-model'
    | '/projects/$projectSlug/admin/contracts'
    | '/projects/$projectSlug/admin/departments'
    | '/projects/$projectSlug/admin/overview'
    | '/projects/$projectSlug/admin/policies'
    | '/projects/$projectSlug/admin/releases'
    | '/projects/$projectSlug/admin/roles'
    | '/projects/$projectSlug/admin/skills'
    | '/projects/$projectSlug/admin/validations'
    | '/projects/$projectSlug/admin/workflows'
    | '/projects/$projectSlug/departments/$departmentId'
    | '/projects/$projectSlug/workflows/$workflowId'
    | '/projects/$projectSlug/workflows/$workflowId/stages/$stageId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/projects/$projectSlug'
    | '/projects/new'
    | '/projects/$projectSlug/admin'
    | '/projects/$projectSlug/diff'
    | '/projects/$projectSlug/org'
    | '/projects/$projectSlug/'
    | '/projects/$projectSlug/admin/agents'
    | '/projects/$projectSlug/admin/audit'
    | '/projects/$projectSlug/admin/capabilities'
    | '/projects/$projectSlug/admin/company-model'
    | '/projects/$projectSlug/admin/contracts'
    | '/projects/$projectSlug/admin/departments'
    | '/projects/$projectSlug/admin/overview'
    | '/projects/$projectSlug/admin/policies'
    | '/projects/$projectSlug/admin/releases'
    | '/projects/$projectSlug/admin/roles'
    | '/projects/$projectSlug/admin/skills'
    | '/projects/$projectSlug/admin/validations'
    | '/projects/$projectSlug/admin/workflows'
    | '/projects/$projectSlug/departments/$departmentId'
    | '/projects/$projectSlug/workflows/$workflowId'
    | '/projects/$projectSlug/workflows/$workflowId/stages/$stageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ProjectsProjectSlugRoute: typeof ProjectsProjectSlugRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectSlug': {
      id: '/projects/$projectSlug'
      path: '/projects/$projectSlug'
      fullPath: '/projects/$projectSlug'
      preLoaderRoute: typeof ProjectsProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectSlug/': {
      id: '/projects/$projectSlug/'
      path: '/'
      fullPath: '/projects/$projectSlug/'
      preLoaderRoute: typeof ProjectsProjectSlugIndexRouteImport
      parentRoute: typeof ProjectsProjectSlugRoute
    }
    '/projects/$projectSlug/org': {
      id: '/projects/$projectSlug/org'
      path: '/org'
      fullPath: '/projects/$projectSlug/org'
      preLoaderRoute: typeof ProjectsProjectSlugOrgRouteImport
      parentRoute: typeof ProjectsProjectSlugRoute
    }
    '/projects/$projectSlug/diff': {
      id: '/projects/$projectSlug/diff'
      path: '/diff'
      fullPath: '/projects/$projectSlug/diff'
      preLoaderRoute: typeof ProjectsProjectSlugDiffRouteImport
      parentRoute: typeof ProjectsProjectSlugRoute
    }
    '/projects/$projectSlug/admin': {
      id: '/projects/$projectSlug/admin'
      path: '/admin'
      fullPath: '/projects/$projectSlug/admin'
      preLoaderRoute: typeof ProjectsProjectSlugAdminRouteImport
      parentRoute: typeof ProjectsProjectSlugRoute
    }
    '/projects/$projectSlug/workflows/$workflowId': {
      id: '/projects/$projectSlug/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/projects/$projectSlug/workflows/$workflowId'
      preLoaderRoute: typeof ProjectsProjectSlugWorkflowsWorkflowIdRouteImport
      parentRoute: typeof ProjectsProjectSlugRoute
    }
    '/projects/$projectSlug/departments/$departmentId': {
      id: '/projects/$projectSlug/departments/$departmentId'
      path: '/departments/$departmentId'
      fullPath: '/projects/$projectSlug/departments/$departmentId'
      preLoaderRoute: typeof ProjectsProjectSlugDepartmentsDepartmentIdRouteImport
      parentRoute: typeof ProjectsProjectSlugRoute
    }
    '/projects/$projectSlug/admin/workflows': {
      id: '/projects/$projectSlug/admin/workflows'
      path: '/workflows'
      fullPath: '/projects/$projectSlug/admin/workflows'
      preLoaderRoute: typeof ProjectsProjectSlugAdminWorkflowsRouteImport
      parentRoute: typeof ProjectsProjectSlugAdminRoute
    }
    '/projects/$projectSlug/admin/validations': {
      id: '/projects/$projectSlug/admin/validations'
      path: '/validations'
      fullPath: '/projects/$projectSlug/admin/validations'
      preLoaderRoute: typeof ProjectsProjectSlugAdminValidationsRouteImport
      parentRoute: typeof ProjectsProjectSlugAdminRoute
    }
    '/projects/$projectSlug/admin/skills': {
      id: '/projects/$projectSlug/admin/skills'
      path: '/skills'
      fullPath: '/projects/$projectSlug/admin/skills'
      preLoaderRoute: typeof ProjectsProjectSlugAdminSkillsRouteImport
      parentRoute: typeof ProjectsProjectSlugAdminRoute
    }
    '/projects/$projectSlug/admin/roles': {
      id: '/projects/$projectSlug/admin/roles'
      path: '/roles'
      fullPath: '/projects/$projectSlug/admin/roles'
      preLoaderRoute: typeof ProjectsProjectSlugAdminRolesRouteImport
      parentRoute: typeof ProjectsProjectSlugAdminRoute
    }
    '/projects/$projectSlug/admin/releases': {
      id: '/projects/$projectSlug/admin/releases'
      path: '/releases'
      fullPath: '/projects/$projectSlug/admin/releases'
      preLoaderRoute: typeof ProjectsProjectSlugAdminReleasesRouteImport
      parentRoute: typeof ProjectsProjectSlugAdminRoute
    }
    '/projects/$projectSlug/admin/policies': {
      id: '/projects/$projectSlug/admin/policies'
      path: '/policies'
      fullPath: '/projects/$projectSlug/admin/policies'
      preLoaderRoute: typeof ProjectsProjectSlugAdminPoliciesRouteImport
      parentRoute: typeof ProjectsProjectSlugAdminRoute
    }
    '/projects/$projectSlug/admin/overview': {
      id: '/projects/$projectSlug/admin/overview'
      path: '/overview'
      fullPath: '/projects/$projectSlug/admin/overview'
      preLoaderRoute: typeof ProjectsProjectSlugAdminOverviewRouteImport
      parentRoute: typeof ProjectsProjectSlugAdminRoute
    }
    '/projects/$projectSlug/admin/departments': {
      id: '/projects/$projectSlug/admin/departments'
      path: '/departments'
      fullPath: '/projects/$projectSlug/admin/departments'
      preLoaderRoute: typeof ProjectsProjectSlugAdminDepartmentsRouteImport
      parentRoute: typeof ProjectsProjectSlugAdminRoute
    }
    '/projects/$projectSlug/admin/contracts': {
      id: '/projects/$projectSlug/admin/contracts'
      path: '/contracts'
      fullPath: '/projects/$projectSlug/admin/contracts'
      preLoaderRoute: typeof ProjectsProjectSlugAdminContractsRouteImport
      parentRoute: typeof ProjectsProjectSlugAdminRoute
    }
    '/projects/$projectSlug/admin/company-model': {
      id: '/projects/$projectSlug/admin/company-model'
      path: '/company-model'
      fullPath: '/projects/$projectSlug/admin/company-model'
      preLoaderRoute: typeof ProjectsProjectSlugAdminCompanyModelRouteImport
      parentRoute: typeof ProjectsProjectSlugAdminRoute
    }
    '/projects/$projectSlug/admin/capabilities': {
      id: '/projects/$projectSlug/admin/capabilities'
      path: '/capabilities'
      fullPath: '/projects/$projectSlug/admin/capabilities'
      preLoaderRoute: typeof ProjectsProjectSlugAdminCapabilitiesRouteImport
      parentRoute: typeof ProjectsProjectSlugAdminRoute
    }
    '/projects/$projectSlug/admin/audit': {
      id: '/projects/$projectSlug/admin/audit'
      path: '/audit'
      fullPath: '/projects/$projectSlug/admin/audit'
      preLoaderRoute: typeof ProjectsProjectSlugAdminAuditRouteImport
      parentRoute: typeof ProjectsProjectSlugAdminRoute
    }
    '/projects/$projectSlug/admin/agents': {
      id: '/projects/$projectSlug/admin/agents'
      path: '/agents'
      fullPath: '/projects/$projectSlug/admin/agents'
      preLoaderRoute: typeof ProjectsProjectSlugAdminAgentsRouteImport
      parentRoute: typeof ProjectsProjectSlugAdminRoute
    }
    '/projects/$projectSlug/workflows/$workflowId/stages/$stageId': {
      id: '/projects/$projectSlug/workflows/$workflowId/stages/$stageId'
      path: '/stages/$stageId'
      fullPath: '/projects/$projectSlug/workflows/$workflowId/stages/$stageId'
      preLoaderRoute: typeof ProjectsProjectSlugWorkflowsWorkflowIdStagesStageIdRouteImport
      parentRoute: typeof ProjectsProjectSlugWorkflowsWorkflowIdRoute
    }
  }
}

interface ProjectsProjectSlugAdminRouteChildren {
  ProjectsProjectSlugAdminAgentsRoute: typeof ProjectsProjectSlugAdminAgentsRoute
  ProjectsProjectSlugAdminAuditRoute: typeof ProjectsProjectSlugAdminAuditRoute
  ProjectsProjectSlugAdminCapabilitiesRoute: typeof ProjectsProjectSlugAdminCapabilitiesRoute
  ProjectsProjectSlugAdminCompanyModelRoute: typeof ProjectsProjectSlugAdminCompanyModelRoute
  ProjectsProjectSlugAdminContractsRoute: typeof ProjectsProjectSlugAdminContractsRoute
  ProjectsProjectSlugAdminDepartmentsRoute: typeof ProjectsProjectSlugAdminDepartmentsRoute
  ProjectsProjectSlugAdminOverviewRoute: typeof ProjectsProjectSlugAdminOverviewRoute
  ProjectsProjectSlugAdminPoliciesRoute: typeof ProjectsProjectSlugAdminPoliciesRoute
  ProjectsProjectSlugAdminReleasesRoute: typeof ProjectsProjectSlugAdminReleasesRoute
  ProjectsProjectSlugAdminRolesRoute: typeof ProjectsProjectSlugAdminRolesRoute
  ProjectsProjectSlugAdminSkillsRoute: typeof ProjectsProjectSlugAdminSkillsRoute
  ProjectsProjectSlugAdminValidationsRoute: typeof ProjectsProjectSlugAdminValidationsRoute
  ProjectsProjectSlugAdminWorkflowsRoute: typeof ProjectsProjectSlugAdminWorkflowsRoute
}

const ProjectsProjectSlugAdminRouteChildren: ProjectsProjectSlugAdminRouteChildren =
  {
    ProjectsProjectSlugAdminAgentsRoute: ProjectsProjectSlugAdminAgentsRoute,
    ProjectsProjectSlugAdminAuditRoute: ProjectsProjectSlugAdminAuditRoute,
    ProjectsProjectSlugAdminCapabilitiesRoute:
      ProjectsProjectSlugAdminCapabilitiesRoute,
    ProjectsProjectSlugAdminCompanyModelRoute:
      ProjectsProjectSlugAdminCompanyModelRoute,
    ProjectsProjectSlugAdminContractsRoute:
      ProjectsProjectSlugAdminContractsRoute,
    ProjectsProjectSlugAdminDepartmentsRoute:
      ProjectsProjectSlugAdminDepartmentsRoute,
    ProjectsProjectSlugAdminOverviewRoute:
      ProjectsProjectSlugAdminOverviewRoute,
    ProjectsProjectSlugAdminPoliciesRoute:
      ProjectsProjectSlugAdminPoliciesRoute,
    ProjectsProjectSlugAdminReleasesRoute:
      ProjectsProjectSlugAdminReleasesRoute,
    ProjectsProjectSlugAdminRolesRoute: ProjectsProjectSlugAdminRolesRoute,
    ProjectsProjectSlugAdminSkillsRoute: ProjectsProjectSlugAdminSkillsRoute,
    ProjectsProjectSlugAdminValidationsRoute:
      ProjectsProjectSlugAdminValidationsRoute,
    ProjectsProjectSlugAdminWorkflowsRoute:
      ProjectsProjectSlugAdminWorkflowsRoute,
  }

const ProjectsProjectSlugAdminRouteWithChildren =
  ProjectsProjectSlugAdminRoute._addFileChildren(
    ProjectsProjectSlugAdminRouteChildren,
  )

interface ProjectsProjectSlugWorkflowsWorkflowIdRouteChildren {
  ProjectsProjectSlugWorkflowsWorkflowIdStagesStageIdRoute: typeof ProjectsProjectSlugWorkflowsWorkflowIdStagesStageIdRoute
}

const ProjectsProjectSlugWorkflowsWorkflowIdRouteChildren: ProjectsProjectSlugWorkflowsWorkflowIdRouteChildren =
  {
    ProjectsProjectSlugWorkflowsWorkflowIdStagesStageIdRoute:
      ProjectsProjectSlugWorkflowsWorkflowIdStagesStageIdRoute,
  }

const ProjectsProjectSlugWorkflowsWorkflowIdRouteWithChildren =
  ProjectsProjectSlugWorkflowsWorkflowIdRoute._addFileChildren(
    ProjectsProjectSlugWorkflowsWorkflowIdRouteChildren,
  )

interface ProjectsProjectSlugRouteChildren {
  ProjectsProjectSlugAdminRoute: typeof ProjectsProjectSlugAdminRouteWithChildren
  ProjectsProjectSlugDiffRoute: typeof ProjectsProjectSlugDiffRoute
  ProjectsProjectSlugOrgRoute: typeof ProjectsProjectSlugOrgRoute
  ProjectsProjectSlugIndexRoute: typeof ProjectsProjectSlugIndexRoute
  ProjectsProjectSlugDepartmentsDepartmentIdRoute: typeof ProjectsProjectSlugDepartmentsDepartmentIdRoute
  ProjectsProjectSlugWorkflowsWorkflowIdRoute: typeof ProjectsProjectSlugWorkflowsWorkflowIdRouteWithChildren
}

const ProjectsProjectSlugRouteChildren: ProjectsProjectSlugRouteChildren = {
  ProjectsProjectSlugAdminRoute: ProjectsProjectSlugAdminRouteWithChildren,
  ProjectsProjectSlugDiffRoute: ProjectsProjectSlugDiffRoute,
  ProjectsProjectSlugOrgRoute: ProjectsProjectSlugOrgRoute,
  ProjectsProjectSlugIndexRoute: ProjectsProjectSlugIndexRoute,
  ProjectsProjectSlugDepartmentsDepartmentIdRoute:
    ProjectsProjectSlugDepartmentsDepartmentIdRoute,
  ProjectsProjectSlugWorkflowsWorkflowIdRoute:
    ProjectsProjectSlugWorkflowsWorkflowIdRouteWithChildren,
}

const ProjectsProjectSlugRouteWithChildren =
  ProjectsProjectSlugRoute._addFileChildren(ProjectsProjectSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ProjectsProjectSlugRoute: ProjectsProjectSlugRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
