apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: the-crew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: the-crew/api-gateway
          ports:
            - containerPort: 4000
          env:
            - name: PLATFORM_SERVICE_URL
              value: http://platform:4010
            - name: COMPANY_DESIGN_SERVICE_URL
              value: http://company-design:4020
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: the-crew
spec:
  selector:
    app: api-gateway
  ports:
    - port: 4000
      targetPort: 4000
