apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: the-crew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: the-crew/web
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: the-crew
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
